version: "3.7"

services:
  bal-ganache:
    build:
      context: ./bal
      target: bal-ethereum
    restart: always
    container_name: bal-ganache
    ports:
      - "8081:8080"
    networks:
      case-study:
        ipv4_address: 172.16.238.10

  ganache-with-truffle:
    container_name: ganache-with-truffle
    build:
      context: ./ganache-cli
      target: ganache
    command:
      [
        "ganache-cli",
        "-m",
        "smart contract composition",
        "--defaultBalanceEther",
        "100000000",
        "-l",
        "471238800",
        "-g",
        "1",
        "-v",
        "--keepAliveTimeout",
        "15000",
        "-b",
        "3",
      ]
    ports:
      - "8545:8545"
    networks:
      case-study:
        ipv4_address: 172.16.238.12

  case-study-backend:
    build:
      context: ./client-app/backend
    restart: always
    container_name: case-study-backend
    ports:
      - "8080:8080"
    environment:
      - CLIENT_CALLBACK_URL=http://case-study-backend:8080
      - DAIRY_BAL_URL=http://172.16.238.11:8080/blockchain-access-layer
      - DAIRY_SC_ADDRESS=mychannel/dairy
      - SEAFOOD_BAL_URL=http://172.16.238.10:8080/blockchain-access-layer
      - SEAFOOD_SC_ADDRESS=0x75f17644EAEb3cC6511764a6F1138F14B3e33D0f
    networks:
      case-study:
        ipv4_address: 172.16.238.17

  nodejs-backend:
    build:
      context: ./client-app/nodejs-backend
    restart: always
    container_name: nodejs-backend
    ports:
      - "3000:3000"
    networks:
      case-study:
        ipv4_address: 172.16.238.18

networks:
  case-study:
    ipam:
      driver: default
      config:
        - subnet: "172.16.238.0/24"
